version: "3"
services:
    web:
        build: 
            context: .
            dockerfile: DataImporter.Web/Dockerfile
        env_file: 
            - web.env
        volumes:
            - dataimporter-data:/app/Logs
        ports:
            - "8000:80"
        depends_on:
            - db
    dataimporterworker:
        build: 
            context: .
            dockerfile: DataImporter.Worker/Dockerfile
        env_file: 
            - web.env
        depends_on: 
            - db 
        volumes:
            - dataimporter-data:/app/Logs
    db:
        image: "mcr.microsoft.com/mssql/server"
        env_file: 
            - web.env
        expose:
            - "1433"
volumes:
     dataimporter-data: 
        external: true
